url: "https://asuracomic.net/"
headless: false
firestore:
  enabled: false
  service_account_credential: "cmd/config/firestore-gcp-access.json"
  collection: "comics-scraper"
  project_id: "my-personal-labs"