url: "https://asuracomic.net/"
description:
max-comics-scrape: 30
headless: false

firestore:
  service_account_credential: "cmd/config/firestore-gcp-access.json"
  collection: "comics-scaraper"
  project_id: "my-personal-labs-395004"